repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: update-readme
        name: update-readme
        entry: python tools/update_readme_help.py
        language: python
        pass_filenames: false
